spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(jBVU2x+RdzbwN47BhcgbcsGuzvaKs6zdYueBVzEPUg07C8p23bErPsY/sj8xat2643OJ9W/wTl8Hw+qyY2GbxTnMoEKEw3yQymwgiiiVk9OF2dnURHGx4/bJVXSfB+2nRZ8OSJus5TM=)
    username: ENC(/uWYvk2R2cc43XZ6SMYJXA==)
    password: ENC(SjClHxff55r8vqUmlga5WbHikAlhBx3k)

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

auth:
  kakao:
    key: ENC(j913dskhw0NaO1Q9FhKWgAyzsobtnUnCgcNx0Zdw38rSuEg4X1JACD/nDOAtjTtd)
    auth-url: https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=${auth.kakao.key}&redirect_uri=http://localhost:3000/callback
    token-url:  https://kauth.kakao.com/oauth/token?client_id={RestAPI Key}&redirect_uri={redirectUrl}&code={받아온 코드}&grant_type=authorization_code
jasypt:
  encryptor:
    password: ${encrypt_key}



app:
  auth:
    tokenExpiry: 172800000
    tokenSecret: gE9hqfKmS3J7VwvP2XZbF6AyGz8L5TQxIOu0NcRs4M1WYnlDpaHtCjvU

cloud:
  aws:
    s3:
      bucket:
        name: ENC(BmrRiXrkt4cNBFnuLhc7BZSslQe9QMheX8YL0kaSyZY=)
        url: ENC(TiiTRG5qecPE5tpatlRysQO/uMizKpbt6P00OZFuM4koINBCnvMG0Oui9y7+cvmRH6tPtuVuGDCtrt0Hp4F2FcBIWO+F3WQj)
    credentials:
      access-key: ENC(Rhh+PzvWrXK/sY8xsj6nZjnseZQLZvXzSy7NaTs7AUY=)
      secret-key: ENC(YILeIgDl09cloXnAqt5W1flFHYHwAoD21Yi2otQ9JqUo9Jo7+Pfiu4fzbBY2U0VkfqqlrxIaup0=)
    region:
      static: ap-northeast-2
    stack:
      auto: false
